package com.darthvader.DungeonServerPlugin.items;

import org.bukkit.*;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.LeatherArmorMeta;

import java.util.ArrayList;
import java.util.List;

public class ItemManager {
    public static ItemStack hyperion;
    public static ItemStack SA_CHESTPLATE;
    public static ItemStack SA_LEGGINGS;
    public static ItemStack SA_SHOES;
    public static ItemStack SA_HELMET;
    public static ItemStack ROTTEN_HELMET;
    public static ItemStack ROTTEN_CHESTPLATE;
    public static ItemStack ROTTEN_LEGGINGS;
    public static ItemStack ROTTEN_BOOTS;
    public static ItemStack ROUGE_SWORD;
    public static ItemStack ENCHANTED_DIAMOND_BLOCK;
    public static ItemStack ENCHANTED_GOLD_BLOCK;
    public static ItemStack ENCHANTED_GOLD_INGOT;
    public static ItemStack ASPECT_OF_THE_END;
    public static ItemStack ASPECT_OF_THE_DRAGONS;
    public static ItemStack ASPECT_OF_THE_VADER;
    public static ItemStack ASPECT_OF_THE_ELEPHANT;
    public static ItemStack WITHER_CLOAK_SWORD;
    public static ItemStack EMERALD_BLADE;
    public static ItemStack EDIBLE_MACE;
    public static ItemStack FLOOR_ONE;
    public static ItemStack NECRONS_HANDLE;
    public static ItemStack REJUVIANTE;
    public static ItemStack REJUVIANTE_THREE;
    public static ItemStack BONEMERANG;
    public static ItemStack BONEMERANG_COOLDOWN;
    public static ItemStack WITHER_SHIELD;
    public static ItemStack IMPLOSION;
    public static ItemStack SHADOW_WARP;
    public static ItemStack WISDOM_THREE;
    public static ItemStack DEATH_BOW;
    public static ItemStack NECRONS_HELMET;
    public static ItemStack NECRONS_CHESTPLATE;
    public static ItemStack NECRONS_LGEGINGS;
    public static ItemStack ZOMBIE_SWORD;

    public static void init() {
        createHyperion();
        createSA_CHESTPLATE();
        createSA_LEGGINGS();
        createSA_SHOES();
        createSA_HELMET();
        createROTTEN_HELMET();
        createROTTEN_CHESTPLATE();
        createROTTEN_LEGGINGS();
        createROTTEN_BOOTS();
        createROUGE_SWORD();
        createENCHANTED_DIAMOND_BLOCK();
        createENCHANTED_GOLD_BLOCK();
        createENCHANTED_GOLD_INGOT();
        createASPECT_OF_THE_END();
        createASPECT_OF_THE_DRAGONS();
        createASPECT_OF_THE_VADER();
        createASPECT_OF_THE_ELEPHANT();
        createWITHER_CLOAK_SWORD();
        createEMERALD_BLADE();
        createEDIBLE_MACE();
        createFLOOR_ONE();
        createNECRONS_HANDLE();
        createREJUVINATE();
        createREJUVINATE_THREE();
        createBONEMERANG();
        createBONEMERANG_COOLDOWN();
        createWISDOM_THREE();
        createSHADOW_WARP();
        createIMPLOSION();
        createWITHER_SHIELD();
        createDEATH_BOW();
        createNECRONS_HELMET();
        createNECRONS_CHESTPLATE();
        createNECRONS_LEGGINGS();
        createZOMBIE_SWORD();
    }
    private static void createHyperion() {
        ItemStack item = new ItemStack(Material.IRON_SWORD, 1);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§6Hyperion");
        List<String> lore = new ArrayList<>();
        lore.add("§7Damage: §c+300");
        lore.add("§7Strength: §c+150");
        lore.add("");
        lore.add("§eItem Ability: Wither Impact §6RIGHT CLICK");
        lore.add("§7Teleport §a10 blocks §7ahead of");
        lore.add("§7you. Then Implode dealing");
        lore.add("§c1000000§7 damage to nearby mobs. ");
        lore.add("§7Also gives you an absorption ");
        lore.add("§7shield of 20 Hearts.");
        lore.add("§8Mana Cost: §b5");
        lore.add("");
        lore.add("§l§6LEGENDARY DUNGEON SWORD");
        meta.setLore(lore);
        meta.addEnchant(Enchantment.DAMAGE_ALL,10, true);
        meta.addEnchant(Enchantment.DAMAGE_UNDEAD,10, true);
        meta.addEnchant(Enchantment.DAMAGE_ARTHROPODS,10, true);
        meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.addItemFlags(ItemFlag.HIDE_DESTROYS);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        meta.setUnbreakable(true);
        item.setItemMeta(meta);
        hyperion = item;
    }
    private static void createROTTEN_HELMET() {
        ItemStack item = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        ItemMeta meta = item.getItemMeta();
        LeatherArmorMeta lml = (LeatherArmorMeta) item.getItemMeta();
        lml.setUnbreakable(true);
        lml.setColor(Color.YELLOW);
        List<String> lore = new ArrayList<>();
        lore.add("§9Protection 5, Growth 5, ");
        lore.add("§9Thorns 3");
        lml.setLore(lore);
        lml.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,4,true);
        lml.addEnchant(Enchantment.THORNS,4,true);
        lml.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        lml.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        lml.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        lml.setDisplayName("§9Rotten Helmet");
        item.setItemMeta(lml);
        ROTTEN_HELMET = item;
    }
    private static void createSA_HELMET() {
        ItemStack item = new ItemStack(Material.LEATHER_HELMET, 1);
        ItemMeta meta = item.getItemMeta();
        LeatherArmorMeta lml = (LeatherArmorMeta) item.getItemMeta();
        lml.setUnbreakable(true);
        lml.setColor(Color.BLACK);
        List<String> lore = new ArrayList<>();
        lore.add("§9Protection 5, Growth 5, ");
        lore.add("§9Thorns 3");
        lml.setLore(lore);
        lml.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,10,true);
        lml.addEnchant(Enchantment.THORNS,4,true);
        lml.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        lml.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        lml.setUnbreakable(true);
        lml.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        lml.setDisplayName("§dShadow Assasin Helmet");
        item.setItemMeta(lml);
        SA_HELMET = item;
    }
    private static void createROTTEN_CHESTPLATE() {
        ItemStack item = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        ItemMeta meta = item.getItemMeta();
        LeatherArmorMeta lml = (LeatherArmorMeta) item.getItemMeta();
        lml.setUnbreakable(true);
        lml.setColor(Color.GREEN);
        List<String> lore = new ArrayList<>();
        lore.add("§9Protection 5, Growth 5, ");
        lore.add("§9Thorns 3");
        lml.setLore(lore);
        lml.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,4,true);
        lml.addEnchant(Enchantment.THORNS,4,true);
        lml.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        lml.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        lml.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        lml.setDisplayName("§9Rotten Chestplate");
        item.setItemMeta(lml);
        ROTTEN_CHESTPLATE = item;
    }
    private static void createROTTEN_LEGGINGS() {
        ItemStack item = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        ItemMeta meta = item.getItemMeta();
        LeatherArmorMeta lml = (LeatherArmorMeta) item.getItemMeta();
        lml.setUnbreakable(true);
        lml.setColor(Color.GREEN);
        List<String> lore = new ArrayList<>();
        lore.add("§9Protection 5, Growth 5, ");
        lore.add("§9Thorns 3");
        lml.setLore(lore);
        lml.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,4,true);
        lml.addEnchant(Enchantment.THORNS,4,true);
        lml.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        lml.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        lml.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        lml.setDisplayName("§9Rotten Leggings");
        item.setItemMeta(lml);
        ROTTEN_LEGGINGS = item;
    }
    private static void createROTTEN_BOOTS() {
        ItemStack item = new ItemStack(Material.LEATHER_BOOTS, 1);
        ItemMeta meta = item.getItemMeta();
        LeatherArmorMeta lml = (LeatherArmorMeta) item.getItemMeta();
        meta.setUnbreakable(true);
        lml.setColor(Color.YELLOW);
        List<String> lore = new ArrayList<>();
        lore.add("§9Protection 5, Growth 5, ");
        lore.add("§9Thorns 3");
        meta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,4,true);
        meta.addEnchant(Enchantment.THORNS,4,true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        meta.setDisplayName("§9Rotten Boots");
        item.setItemMeta(meta);
        ROTTEN_BOOTS = item;
    }
    private static void createROUGE_SWORD() {
        ItemStack item = new ItemStack(Material.GOLDEN_SWORD, 1);
        ItemMeta meta = item.getItemMeta();
        meta.setUnbreakable(true);
        meta.addEnchant(Enchantment.DAMAGE_ALL, 5, true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        meta.setDisplayName("§7Rouge Sword");
        item.setItemMeta(meta);
        ROUGE_SWORD = item;
    }
    private static void createENCHANTED_DIAMOND_BLOCK() {
        ItemStack item = new ItemStack(Material.DIAMOND_BLOCK, 1);
        ItemMeta meta = item.getItemMeta();
        meta.addEnchant(Enchantment.LUCK, 1, false);
        List<String> lore = new ArrayList<>();
        lore.add("§9§nRARE");
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.setDisplayName("§9Enchanted Diamond Block");
        item.setItemMeta(meta);
        ENCHANTED_DIAMOND_BLOCK = item;
    }
    private static void createENCHANTED_GOLD_BLOCK() {
        ItemStack item = new ItemStack(Material.GOLD_BLOCK, 1);
        ItemMeta meta = item.getItemMeta();
        meta.addEnchant(Enchantment.LUCK, 1, false);
        List<String> lore = new ArrayList<>();
        lore.add("§9§nRARE");
        meta.setDisplayName("§9Enchanted Gold Block");
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        item.setItemMeta(meta);
        ENCHANTED_GOLD_BLOCK = item;
    }
    private static void createENCHANTED_GOLD_INGOT() {
        ItemStack item = new ItemStack(Material.GOLD_INGOT, 1);
        ItemMeta meta = item.getItemMeta();
        meta.addEnchant(Enchantment.LUCK, 1, false);
        List<String> lore = new ArrayList<>();
        lore.add("§a§nUncommon");
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.setDisplayName("§aEnchanted Gold Ingot");
        item.setItemMeta(meta);
        ENCHANTED_GOLD_INGOT = item;
    }
    private static void createASPECT_OF_THE_END() {
        ItemStack item = new ItemStack(Material.DIAMOND_SWORD);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§9Aspect Of The End");
        meta.addEnchant(Enchantment.DAMAGE_ALL, 6, true);
        List<String> lore = new ArrayList<>();
        lore.add("§7Damage: §c+100");
        lore.add("§7Strength: §c+100");
        lore.add("");
        lore.add("§eItem Ability: Instant Transmission §6RIGHT CLICK");
        lore.add("§7Teleport §a8 §7blocks ahead of");
        lore.add("§7you and gain §a+50 §fSpeed");
        lore.add("§7§7for §a3 seconds§7.");
        lore.add("§8Mana Cost: §b2");
        lore.add("§9RARE SWORD");
        meta.setUnbreakable(true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        meta.setLore(lore);
        item.setItemMeta(meta);
        ASPECT_OF_THE_END = item;
        }
        private static void createASPECT_OF_THE_DRAGONS() {
        ItemStack item = new ItemStack(Material.DIAMOND_SWORD);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§6Aspect of the Dragons");
        List<String> lore = new ArrayList<>();
        lore.add("§7Damage: §c+225");
        lore.add("§7Strength: §c+100");
        lore.add("");
        lore.add("§eItem Ability: Dragon Rage §6RIGHT CLICK");
        lore.add("§7All monsters in front of you");
        lore.add("§7take §a700 §7damage. Hit");
        lore.add("§7monsters also take large knockback.");
        lore.add("§8Mana Cost: §b100");
        lore.add("§8Cooldown: §a5s");
        lore.add("§6LENGENDARY SWORD");
        meta.addEnchant(Enchantment.DAMAGE_ALL, 7, true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.setUnbreakable(true);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        meta.setLore(lore);
        item.setItemMeta(meta);
        ASPECT_OF_THE_DRAGONS = item;
        }
        private static void createASPECT_OF_THE_VADER() {
        ItemStack item = new ItemStack(Material.GOLDEN_SWORD);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§cAspect of the Vader");
        List<String> lore = new ArrayList<>();
        lore.add("§7Damage: §c+32767");
        lore.add("§7Strength: §c+32767");
        lore.add("");
        lore.add("§eItem Ability: The Dark Side §6RIGHT CLICK");
        lore.add("§7Teleport §a8 §7blocks ahead of");
        lore.add("§7you and gain §a+50 §fSpeed");
        lore.add("§7§7for §a3 seconds§7.");
        lore.add("§7Then gain invincibility for");
        lore.add("§75 seconds and an absorption");
        lore.add("§7shield for one minute.");
        lore.add("§8Mana Cost: §b0");
        lore.add("§cSPECIAL SWORD");
        meta.setUnbreakable(true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        meta.setLore(lore);
        meta.addEnchant(Enchantment.DAMAGE_ALL, 32767, true);
        meta.addEnchant(Enchantment.DAMAGE_UNDEAD, 32767, true);
        meta.addEnchant(Enchantment.DAMAGE_ARTHROPODS, 32767, true);
        item.setItemMeta(meta);
        ASPECT_OF_THE_VADER = item;
        }
        private static void createASPECT_OF_THE_ELEPHANT() {
        ItemStack item = new ItemStack(Material.GOLDEN_SWORD);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§cAspect of the Elephant");
        meta.setUnbreakable(true);
        meta.addEnchant(Enchantment.DAMAGE_ALL, 999, true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        List<String> lore = new ArrayList<>();
        lore.add("§7Damage: §c+ 999");
        lore.add("§7Strength: §c+100");
        lore.add("");
        lore.add("§eItem Ability: Elephant Stomp §6RIGHT CLICK");
        lore.add("§7Create a hole beneath");
        lore.add("§7you when right clicking");
        lore.add("§7any block. Pretty pointless");
        lore.add("§7Am I right.");
        lore.add("§8Mana Cost: §b0");
        lore.add("§cSPECIAL SWORD");
        meta.setLore(lore);
        item.setItemMeta(meta);
        ASPECT_OF_THE_ELEPHANT = item;
        }
        private static void createWITHER_CLOAK_SWORD() {
        ItemStack item = new ItemStack(Material.STONE_SWORD);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§5Wither Cloak Sword");
        meta.addEnchant(Enchantment.DAMAGE_ALL, 5, true);
        meta.setUnbreakable(true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        List<String> lore = new ArrayList<>();
        lore.add("§7Damage: §c+190");
        lore.add("§7Strength: §c+135");
        lore.add("");
        lore.add("§7Defense: §a+250");
        lore.add("");
        lore.add("§eItem Ability: Creeper Veil §6RIGHT CLICK");
        lore.add("§7Spawns a creeper veil around you that");
        lore.add("§7grants you immunity from damage.");
        lore.add("§7Costs §d20% §7of your maximum");
        lore.add("§7mana each time you block a hit.");
        lore.add("§7Unable to attack while the");
        lore.add("§7shield is active but your");
        lore.add("§7creepers deal §c200§7 damage to");
        lore.add("§7nearby enemies every second.");
        lore.add("§7Deactivates after one minute.");
        meta.setLore(lore);
        item.setItemMeta(meta);
        WITHER_CLOAK_SWORD = item;
        }
        private static void createEMERALD_BLADE() {
            ItemStack item = new ItemStack(Material.EMERALD);
            ItemMeta meta = item.getItemMeta();
            meta.setDisplayName("§5Emerald Blade");
            meta.addEnchant(Enchantment.DAMAGE_ALL, 25, true);
            meta.setUnbreakable(true);
            List<String> lore = new ArrayList<>();
            lore.add("§7Damage: §c+999");
            lore.add("");
            lore.add("§7A powerful blade made from pure");
            lore.add("§aEmeralds§7. This blade becomes stronger as you carry more");
            lore.add("§6coins §7in your purse.");
            lore.add("");
            lore.add("§7Current Damage Bonus: §a999.9");
            meta.setLore(lore);
            meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
            item.setItemMeta(meta);
            EMERALD_BLADE = item;
        }
        private static void createEDIBLE_MACE() {
        ItemStack item = new ItemStack(Material.MUTTON);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§9Edible Mace");
        List<String> lore = new ArrayList<>();
        lore.add("§7Damage: §c+125");
        lore.add("§7Strength: §c+25");
        lore.add("");
        lore.add("§6Item Ability: ME SMASH HERO §eRIGHT CLICK");
        lore.add("§7Your next attack deals §cdouble");
        lore.add("§cdamage §7and weakens animals,");
        lore.add("§7making them deal §c-35% §7damage");
        lore.add("§7for §a30 §7seconds");
        lore.add("§8Debuff doesn't stack");
        lore.add("§8Mana Cost: §b100");
        meta.setLore(lore);
        item.setItemMeta(meta);
        EDIBLE_MACE = item;
        }
        private static void createFLOOR_ONE() {
        ItemStack item = new ItemStack(Material.GREEN_CONCRETE);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§aThe Catacombs §8- §eFloor I");
        meta.addEnchant(Enchantment.LUCK, 1, true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        List<String> lore = new ArrayList<>();
        lore.add("§7Dungeon Size: §bTiny");
        lore.add("§7Party Size: §94-5");
        lore.add("");
        lore.add("§7Boss: §cBonzo §a✔");
        lore.add("§8New Necromancer");
        lore.add("§7Involved in the dark arts due to his");
        lore.add("§7parents' insistence. Originally worked as");
        lore.add("§7a Circus clown");
        lore.add("");
        lore.add("§7Requires: §bCombat Level 6");
        meta.setLore(lore);
        item.setItemMeta(meta);
        FLOOR_ONE = item;
        }
        private static void createFLOOR_SEVEN() {
        ItemStack item = new ItemStack(Material.BLUE_CONCRETE);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§aThe Catacombs §8- §eFloor VII");
        }
        private static void createNECRONS_HANDLE() {
        ItemStack item = new ItemStack(Material.STICK);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§5Necron's Handle");
        meta.addEnchant(Enchantment.LUCK, 1, false);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        List<String> lore = new ArrayList<>();
        lore.add("§eRight-click to view recipes!");
        lore.add("");
        lore.add("§5EPIC DUNGEON ITEM");
        meta.setLore(lore);
        item.setItemMeta(meta);
        NECRONS_HANDLE = item;
        }
        private static void createREJUVINATE() {
        ItemStack item = new ItemStack(Material.ENCHANTED_BOOK);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§fEnchanted Book");
        meta.addEnchant(Enchantment.LUCK, 1, false);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        List<String> lore = new ArrayList<>();
        lore.add("§9Rejuvinate I");
        lore.add("§7Increases your natural");
        lore.add("§7regeneration by §a+2%");
        lore.add("");
        lore.add("§7Sell this item for sunflowers!");
        lore.add("§f§lCOMMON");
        meta.setLore(lore);
        item.setItemMeta(meta);
        REJUVIANTE = item;
        }
    private static void createREJUVINATE_THREE() {
        ItemStack item = new ItemStack(Material.ENCHANTED_BOOK);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§fEnchanted Book");
        meta.addEnchant(Enchantment.LUCK, 1, false);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        List<String> lore = new ArrayList<>();
        lore.add("§9Rejuvinate III");
        lore.add("§7Increases your natural");
        lore.add("§7regeneration by §a+6%");
        lore.add("");
        lore.add("§7Sell this item for sunflowers!");
        lore.add("§f§lCOMMON");
        meta.setLore(lore);
        item.setItemMeta(meta);
        REJUVIANTE_THREE = item;
    }
    private static void createWISDOM_THREE() {
        ItemStack item = new ItemStack(Material.ENCHANTED_BOOK);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§fEnchanted Book");
        meta.addEnchant(Enchantment.LUCK, 1, false);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        List<String> lore = new ArrayList<>();
        lore.add("§9Wisdom III");
        lore.add("§7Gain §a3 §bIntelligence §7per");
        lore.add("§7level, for every §a5§7 levels");
        lore.add("§7of exp you have on you. Capped");
        lore.add("§7at §a60 §bIntelligence §7per level.");
        lore.add("");
        lore.add("§7Sell this item for sunflowers!");
        lore.add("§5§lEPIC DUNGEON BOOK");
        meta.setLore(lore);
        item.setItemMeta(meta);
        WISDOM_THREE = item;
    }
    private static void createBONEMERANG() {
        ItemStack item = new ItemStack(Material.BONE);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§6Bonemerang");
        List<String> lore = new ArrayList<>();
        lore.add("§7Damage: §c+320");
        lore.add("§7Strength: §c+130");
        lore.add("§7Crit Chance: §c+5");
        lore.add("§7Crit Damage: §c+5%");
        lore.add("");
        lore.add("§6Item Ability: Swing §eRIGHT CLICK");
        lore.add("§7Throw the bone a short distance,");
        lore.add("§7dealing the damage an arrow");
        lore.add("§7would.");
        lore.add("");
        lore.add("§7Deals §cdouble damage §7when");
        lore.add("§7comming back. Pierces up to §e10");
        lore.add("§7foes.");
        lore.add("");
        lore.add("§l§6LEGENDARY DUNGEON BOW");
        meta.setLore(lore);
        meta.addEnchant(Enchantment.DAMAGE_ALL, 10, true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        item.setItemMeta(meta);
        BONEMERANG = item;
    }
    private static void createBONEMERANG_COOLDOWN() {
        ItemStack item = new ItemStack(Material.GHAST_TEAR);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§6Bonemerang");
        List<String> lore = new ArrayList<>();
        lore.add("§7Damage: §c+320");
        lore.add("§7Strength: §c+130");
        lore.add("§7Crit Chance: §c+5");
        lore.add("§7Crit Damage: §c+5%");
        lore.add("");
        lore.add("§6Item Ability: Swing §eRIGHT CLICK");
        lore.add("§7Throw the bone a short distance,");
        lore.add("§7dealing the damage an arrow");
        lore.add("§7would.");
        lore.add("");
        lore.add("§7Deals §cdouble damage §7when");
        lore.add("§7comming back. Pierces up to §e10");
        lore.add("§7foes.");
        lore.add("");
        lore.add("§cThis item is on cooldown!");
        lore.add("");
        lore.add("§l§6LEGENDARY DUNGEON BOW");
        meta.setLore(lore);
        meta.addEnchant(Enchantment.DAMAGE_ALL, 10, true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        item.setItemMeta(meta);
        BONEMERANG_COOLDOWN = item;
    }
    private static void createSTORM_HELMET() {
        ItemStack item =  new ItemStack(Material.LEATHER_HELMET);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§6Storm's Helmet");
        List<String> lore = new ArrayList<>();
        lore.add("§7Gear Score: §5565");
        lore.add("§7Health: §a+180 HP");
        lore.add("§7Defense: §a+80");
        lore.add("§7Intelligence: §a+250");
        lore.add("");
        lore.add("§6Full Set Bonus: Witherborn");
        lore.add("§7Spawns a wither minion every");
        lore.add("§e30 §7seconds up to a");
        lore.add("§7maximum §a1 §7wither. Your withers will");
        lore.add("§7travel to and explode on nearby enimies.");
        lore.add("");
        lore.add("§l§6LEGENDARY DUNGEON ARMOR");
    }
    private static void createSHADOW_WARP() {
        ItemStack item = new ItemStack(Material.WRITTEN_BOOK);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§5Shadow Warp");
        meta.addEnchant(Enchantment.LUCK, 1, true);
        List<String> lore = new ArrayList<>();
        lore.add("§7This scroll can be combined");
        lore.add("§7with all the other scrolls");
        lore.add("§7to be applied to §6Necron's Blade");
        lore.add("§6(Unbrefined) §7granting it the");
        lore.add("§7the §6Shadow Warp");
        lore.add("§7ability.");
        lore.add("");
        lore.add("§5EPIC DUNGEON ITEM");
        meta.setLore(lore);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        item.setItemMeta(meta);
        SHADOW_WARP = item;
    }
    private static void createWITHER_SHIELD() {
        ItemStack item = new ItemStack(Material.WRITTEN_BOOK);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§5Wither Shield");
        meta.addEnchant(Enchantment.LUCK, 1, true);
        List<String> lore = new ArrayList<>();
        lore.add("§7This scroll can be combined");
        lore.add("§7with all the other scrolls");
        lore.add("§7to be applied to §6Necron's Blade");
        lore.add("§6(Unbrefined) §7granting it the");
        lore.add("§7the §6Wither Shield");
        lore.add("§7ability.");
        lore.add("");
        lore.add("§5EPIC DUNGEON ITEM");
        meta.setLore(lore);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        item.setItemMeta(meta);
        WITHER_SHIELD = item;
    }
    private static void createIMPLOSION() {
        ItemStack item = new ItemStack(Material.WRITTEN_BOOK);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§5Implosion");
        meta.addEnchant(Enchantment.LUCK, 1, true);
        List<String> lore = new ArrayList<>();
        lore.add("§7This scroll can be combined");
        lore.add("§7with all the other scrolls");
        lore.add("§7to be applied to §6Necron's Blade");
        lore.add("§6(Unbrefined) §7granting it the");
        lore.add("§7the §6Implosion");
        lore.add("§7ability.");
        lore.add("");
        lore.add("§5EPIC DUNGEON ITEM");
        meta.setLore(lore);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        item.setItemMeta(meta);
        IMPLOSION = item;
    }
    private static void createDEATH_BOW() {
        ItemStack item = new ItemStack(Material.BOW);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("§5Death Bow");
        meta.addEnchant(Enchantment.ARROW_DAMAGE, 8, true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        meta.setUnbreakable(true);
        List<String> lore = new ArrayList<>();
        lore.add("§7Gear Score: §d340");
        lore.add("§7Damage: §c+300");
        lore.add("");
        lore.add("§7Deals §a+100% §cdamage §7to");
        lore.add("§aUndead monsters§7.");
        lore.add("");
        lore.add("§7Your arrows have a §e50.0%");
        lore.add("§7chance to bounce to another");
        lore.add("§7target after it hits something.");
        lore.add("");
        lore.add("§l§5EPIC DUNGEON BOW");
        meta.setLore(lore);
        item.setItemMeta(meta);
        DEATH_BOW = item;
    }
    private static void createSA_CHESTPLATE() {
        ItemStack item = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        LeatherArmorMeta lml = (LeatherArmorMeta) item.getItemMeta();
        lml.setUnbreakable(true);
        lml.setColor(Color.BLACK);
        lml.setDisplayName("§5Shadow Assassin Chestplate");
        List<String> lore = new ArrayList<>();
        lore.add("§7Gear Score: §d530");
        lore.add("§7Strength: §c+25");
        lore.add("§7Crit Damage: §c+25%");
        lore.add("");
        lore.add("§7Health: §a+240 HP");
        lore.add("§7Defense: §a+110");
        lore.add("§7Speed: §a+7");
        lore.add("");
        lore.add("§6Full Set Bonus: Shadow Assassin");
        lore.add("§7Collect the shadows of the");
        lore.add("§7enemies you kill increasing your");
        lore.add("§7damage for the rest of the");
        lore.add("§7dungeon while wearing this set.");
        lore.add("§c+1 Strength §7every kill.");
        lml.setLore(lore);
        lml.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,10,true);
        lml.addEnchant(Enchantment.THORNS,4,true);
        lml.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        lml.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        lml.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        item.setItemMeta(lml);
        SA_CHESTPLATE = item;
    }
    private static void createSA_LEGGINGS() {
        ItemStack item = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        ItemMeta meta = item.getItemMeta();
        LeatherArmorMeta lml = (LeatherArmorMeta) item.getItemMeta();
        meta.setUnbreakable(true);
        lml.setColor(Color.BLACK);
        item.setItemMeta(lml);
        List<String> lore = new ArrayList<>();
        lore.add("§9Protection 5, Growth 5, ");
        lore.add("§9Thorns 3");
        meta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,10,true);
        meta.addEnchant(Enchantment.THORNS,4,true);
        meta.setDisplayName("§dShadow Assassin Leggings");
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        item.setItemMeta(meta);
        SA_LEGGINGS = item;
    }
    private static void createSA_SHOES() {
        ItemStack item = new ItemStack(Material.LEATHER_BOOTS, 1);
        ItemMeta meta = item.getItemMeta();
        LeatherArmorMeta lml = (LeatherArmorMeta) item.getItemMeta();
        meta.setUnbreakable(true);
        lml.setColor(Color.BLACK);
        item.setItemMeta(lml);
        List<String> lore = new ArrayList<>();
        lore.add("§9Protection                                                     5, Growth 5, ");
        lore.add("§9Thorns 3");
        meta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL,10,true);
        meta.addEnchant(Enchantment.THORNS,4,true);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        meta.setDisplayName("§dShadow Assassin Boots");
        meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        item.setItemMeta(meta);
        SA_SHOES = item;
    }
    private static void createNECRONS_HELMET() {
        ItemStack item = new ItemStack(Material.LEATHER_HELMET);
        LeatherArmorMeta meta = (LeatherArmorMeta) item.getItemMeta();
        meta.setColor(Color.RED);
        meta.setUnbreakable(true);
        meta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL, 18, true);
        meta.addEnchant(Enchantment.THORNS, 4, true);
        meta.setDisplayName("§6Necron's Helmet");
        List<String> lore = new ArrayList<>();
        lore.add("§7Gear Score: §d484");
        lore.add("§7Strength: §c+40");
        lore.add("§7Crit Damage: §c+30%");
        lore.add("");
        lore.add("§7Health: §a+180 HP");
        lore.add("§7Defense: §a+100");
        lore.add("§7Intelligence: +30");
        lore.add("");
        lore.add("§6Full Set Bonus: Witherborn §cCurrently In Development");
        lore.add("§7Spawns a wither minion every");
        lore.add("§e30 §7seconds up to a");
        lore.add("§7maximum §a1 §7wither. Your withers will");
        lore.add("§7travel to and explode on nearby");
        lore.add("§7enemies");
        lore.add("");
        lore.add("§7Reduces the damage you take");
        lore.add("§7from withers by §c10%§7.");
        lore.add("");
        lore.add("§6§lLEGENDARY DUNGEON HELMET");
        meta.setLore(lore);
        item.setItemMeta(meta);
        NECRONS_HELMET = item;
    }
    private static void createNECRONS_CHESTPLATE() {
        ItemStack item = new ItemStack(Material.LEATHER_CHESTPLATE);
        LeatherArmorMeta meta = (LeatherArmorMeta) item.getItemMeta();
        meta.setColor(Color.RED);
        meta.setUnbreakable(true);
        meta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL, 18, true);
        meta.addEnchant(Enchantment.THORNS, 4, true);
        meta.setDisplayName("§6Necron's Chestplate");
        List<String> lore = new ArrayList<>();
        lore.add("§7Gear Score: §d634");
        lore.add("§7Strength: §c+40");
        lore.add("§7Crit Damage: §c+30%");
        lore.add("");
        lore.add("§7Health: §a+260 HP");
        lore.add("§7Defense: §a+140");
        lore.add("§7Intelligence: +10");
        lore.add("");
        lore.add("§6Full Set Bonus: Witherborn §cCurrently In Development");
        lore.add("§7Spawns a wither minion every");
        lore.add("§e30 §7seconds up to a");
        lore.add("§7maximum §a1 §7wither. Your withers will");
        lore.add("§7travel to and explode on nearby");
        lore.add("§7enemies");
        lore.add("");
        lore.add("§7Reduces the damage you take");
        lore.add("§7from withers by §c10%§7.");
        lore.add("");
        lore.add("§6§lLEGENDARY DUNGEON CHESTPLATE");
        meta.setLore(lore);
        item.setItemMeta(meta);
        NECRONS_CHESTPLATE = item;
    }
    private static void createNECRONS_LEGGINGS() {
        ItemStack item = new ItemStack(Material.LEATHER_LEGGINGS);
        LeatherArmorMeta meta = (LeatherArmorMeta) item.getItemMeta();
        meta.setColor(Color.RED);
        meta.setUnbreakable(true);
        meta.addEnchant(Enchantment.PROTECTION_ENVIRONMENTAL, 18, true);
        meta.addEnchant(Enchantment.THORNS, 4, true);
        meta.setDisplayName("§6Necron's Chestplate");
        List<String> lore = new ArrayList<>();
        lore.add("§7Gear Score: §d574");
        lore.add("§7Strength: §c+40");
        lore.add("§7Crit Damage: §c+30%");
        lore.add("");
        lore.add("§7Health: §a+230 HP");
        lore.add("§7Defense: §a+125");
        lore.add("§7Intelligence: +10");
        lore.add("");
        lore.add("§6Full Set Bonus: Witherborn §cCurrently In Development");
        lore.add("§7Spawns a wither minion every");
        lore.add("§e30 §7seconds up to a");
        lore.add("§7maximum §a1 §7wither. Your withers will");
        lore.add("§7travel to and explode on nearby");
        lore.add("§7enemies");
        lore.add("");
        lore.add("§7Reduces the damage you take");
        lore.add("§7from withers by §c10%§7.");
        lore.add("");
        lore.add("§6§lLEGENDARY DUNGEON CHESTPLATE");
        meta.setLore(lore);
        item.setItemMeta(meta);
        NECRONS_LGEGINGS = item;
    }
    private static void createZOMBIE_SWORD() {
        ItemStack item = new ItemStack(Material.GOLDEN_SWORD);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("Zombie Sword");
        meta.setUnbreakable(true);
        meta.addEnchant(Enchantment.DAMAGE_ALL, 2, true);
        meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
        item.setItemMeta(meta);
        ZOMBIE_SWORD = item;
    }
}