name: GrubHubItems
version: 1.1
author: darthvader
main: com.darthvader.GrubHubItems.GrubHubItems
api-version: 1.14
commands:
  givewand:
    description: Give custom wand to player.
    usage: /<command>
  isdarthcool:
    description: Is darth cool or not?
    usage: /<command>
  gmc:
    description: Puts your gamemode into creative.
    usage: /<command>
  gms:
    description: Puts your gamemode into survival.
    usage: /<command>
  gmsp:
    description: Puts you in spectator mode.
    usage: /<command>
  fly:
    description: Allows the player to fly
    usage: /<command>
  givehyperion:
    description: Gives you a hyperion
    usage: /<command>
  items:
    description: Opens up a GUI with all of the custom items.
    usage: /<command>
  shadowassasin:
    description: Gives you shadow assasin armor
    usage: /<command>
  bz:
    description: Bazaar
    usage: /<command>
  rougesword:
    description: Get a rouge sword
    usage: /<commnad>
  aote:
    description: Get an aspect of the end
    usage: /<command>
  aotd:
    description: Get an aspect of the dragons
    usage: /<command>
  heal:
    description: Heal
    usage: /<command>
  aotv:
    description: Get an aspect of the vader
    usage: /<command>
  aotelephant:
    description: Get an aspect of the elephant
    usage: /<command>
  withercloak:
    description: Get a wtiher cloak sword
    usage: /<command>
  emeraldblade:
    description: Get an emerald blade
    usage: /<command>
  brodcast:
    description: brodcast a message to all players
    usage: /<command>
  mace:
    description: get an edible mace
    usage: /<command>
  nick:
    description: nick
    usage: /<command>
  nickreset:
    description: reset nick
    usage: /<command>
  handle:
    description: get handle
    usage: /<command>
  bone:
    description: get bonemerang
    usage: /<command>
  necron:
    description: summon necron
    usage: /<command>
  ban:
    description: Ban a player. /ban <player> <reason>
    usage: /<command>
  unban:
    description: Unban a player. /unban <player>
    usage: /<command>
  deathbow:
    description: get a death bow
    usage: /<command>
  golem:
    description: spawn a golem
    usage: /<command>
  la:
    description: Spawn lost adventurer
    usage: /<command>
  zombiesword:
    description: Get a zombie sword
    usage: /<command>